# Generated by Django 4.2.2 on 2023-06-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=303)),
                ('title_ru', models.CharField(max_length=303, null=True)),
                ('title_uz', models.CharField(max_length=303, null=True)),
                ('title_en', models.CharField(max_length=303, null=True)),
                ('image', models.FileField(upload_to='course/')),
                ('price', models.CharField(max_length=202)),
                ('duration', models.CharField(max_length=202)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=404)),
                ('title_ru', models.CharField(max_length=404, null=True)),
                ('title_uz', models.CharField(max_length=404, null=True)),
                ('title_en', models.CharField(max_length=404, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('title_ru', models.CharField(max_length=202, null=True)),
                ('title_uz', models.CharField(max_length=202, null=True)),
                ('title_en', models.CharField(max_length=202, null=True)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Wrong Answer', 'Wrong Answer'), ('Accepted', 'Accepted')], default='Waiting', max_length=404)),
                ('code', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='course.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('input_ru', models.TextField(null=True)),
                ('input_uz', models.TextField(null=True)),
                ('input_en', models.TextField(null=True)),
                ('output', models.TextField()),
                ('output_ru', models.TextField(null=True)),
                ('output_uz', models.TextField(null=True)),
                ('output_en', models.TextField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_examples', to='course.task')),
            ],
        ),
    ]
