# Generated by Django 4.2.2 on 2023-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=909)),
                ('title_ru', models.CharField(max_length=909, null=True)),
                ('title_uz', models.CharField(max_length=909, null=True)),
                ('title_en', models.CharField(max_length=909, null=True)),
                ('image', models.FileField(upload_to='abouts/')),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=202)),
                ('phone', models.CharField(max_length=202)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='goals/')),
                ('title', models.CharField(max_length=202)),
                ('title_ru', models.CharField(max_length=202, null=True)),
                ('title_uz', models.CharField(max_length=202, null=True)),
                ('title_en', models.CharField(max_length=202, null=True)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
            ],
        ),
    ]
