# Generated by Django 4.2.2 on 2023-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
